# permissions for end users to view inferenceservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inferenceservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kai
    app.kubernetes.io/part-of: kai
    app.kubernetes.io/managed-by: kustomize
  name: inferenceservice-viewer-role
rules:
- apiGroups:
  - ai.kai.io
  resources:
  - inferenceservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ai.kai.io
  resources:
  - inferenceservices/status
  verbs:
  - get
