apiVersion: core.kai.io/v1alpha1
kind: Version
metadata:
  labels:
    app.kubernetes.io/name: version
    app.kubernetes.io/instance: version-sample
    app.kubernetes.io/part-of: kai
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kai
  name: version-sample
spec:
  # TODO(user): Add fields here
