name: E2E Tests

on:
  pull_request:
    branches: [main]
    paths:
      - '**'
      - '!.github/**'
      - '!docs/**'
      - '!**.md'
      - '.github/workflows/e2e.yaml'

env:
   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  kai-controller-image-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build kai images
        run: make docker-build VERSION=${{ github.sha }}

      - name: Upload controller image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: "dreamstax/kai-controller:${{ github.sha }}"

  test-fast:
    runs-on: ubuntu-latest
    needs: [kai-controller-image-build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19.4'

      - name: Download kai-controller image
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: "dreamstax/kai-controller:${{ github.sha }}"

      - name: Install Kai
        run: |
          make deps cluster manifests generate build docker-load deploy VERSION=${{ github.sha }}
          ./scripts/wait-for.sh